// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

//Esse layout sera o padrão que irá carregar em toda página, caso eu queira sobrescrever. Criar arquivo layout dentro da página sugerida

// import "./layout.css"; //Maneira de importar css global
export default function RootLayout({ children }) {
  return (
    <>
      <html lang="pt-br">
        <head>
          {/* Outra maneira de colocar css global */}
          <style>{`
      * {
        color: blue;
  font-family: sans-serif;
  font-size: 1em;
      }
    `}</style>
          <title>Next.js - Home</title>
        </head>
        <body>{children}</body>
      </html>
    </>
  );
}
