// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head><title>Next.js - Home</title></head>
      <body>{children}</body>
    </html>
  );
}
